#!/usr/bin/env node
/**
 * Generate the reference indexes under `docs/generated/`.
 *
 * Two documents are produced from the profiles themselves rather than written by
 * hand, because hand-maintained indexes drift and a drifted index is worse than no
 * index: it tells a reader that a requirement set covers something it does not.
 *
 * - `profile-index.md` lists every profile with its lifecycle status, the upstream
 *   revision it pins, how many of each requirement it declares, and the digest of
 *   its vector corpus.
 * - `vector-index.md` lists every vector with its profile, kind, method and
 *   location, so a reader can find the case that covers a given requirement.
 *
 * `--check` regenerates in memory and compares against what is on disk. CI uses it
 * so that a profile change which alters the index cannot be merged without the
 * regenerated index, which is what keeps the committed documents truthful.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

import {
  booleanFlag,
  COMMON_FLAGS,
  combineDigests,
  DiagnosticBag,
  digestOfValue,
  discoverProfileDirectories,
  ErrorCode,
  EXIT_CODES,
  GENERATED_DOCS_DIR,
  getSchemaRegistry,
  handleCliError,
  loadProfileBundle,
  loadVectors,
  parseArgs,
  prettyJson,
  PROFILES_DIR,
  readdirSyncSafe,
  reportSummary,
  REPO_ROOT,
  success,
  usage,
  VECTORS_DIR,
  type LoadedVector,
  type ProfileBundle,
} from "./lib/index.ts";

const PROGRAM = "estamora-generate-docs";

const DESCRIPTION = "Generate the reference indexes under docs/generated/.";

const FLAGS = [
  ...COMMON_FLAGS,
  {
    name: "check",
    type: "boolean" as const,
    description: "Fail if the committed documents differ from the generated ones",
  },
];

/** Banner placed at the top of every generated document. */
const BANNER =
  "<!-- Generated by scripts/generate-docs.ts. Do not edit by hand. Run `npm run docs:generate`. -->";

interface VectorRow {
  readonly id: string;
  readonly profile: string;
  readonly version: string;
  readonly kind: string;
  readonly method: string;
  readonly location: string;
}

function main(argv: readonly string[]): number {
  const args = parseArgs(argv, FLAGS);
  if (booleanFlag(args, "help")) {
    process.stdout.write(`${usage(PROGRAM, DESCRIPTION, FLAGS)}\n`);
    return EXIT_CODES.SUCCESS;
  }

  const check = booleanFlag(args, "check");
  const bag = new DiagnosticBag();
  const registry = getSchemaRegistry();

  const bundles = discoverProfileDirectories(PROFILES_DIR)
    .map((directory) => loadProfileBundle(directory, registry, new DiagnosticBag()))
    .filter((bundle) => bundle.valid && bundle.profile !== undefined);

  const sharedVectors: LoadedVector[] = [];
  for (const [, files] of readSharedVectorFiles()) {
    sharedVectors.push(...loadVectors(files, registry, new DiagnosticBag()));
  }

  const outputs = new Map<string, string>([
    ["profile-index.md", renderProfileIndex(bundles)],
    ["vector-index.md", renderVectorIndex(bundles, sharedVectors)],
  ]);

  if (check) {
    for (const [name, content] of outputs) {
      const path = join(GENERATED_DOCS_DIR, name);
      if (!existsSync(path)) {
        bag.error(
          ErrorCode.DOCS_OUT_OF_DATE,
          `Generated document ${JSON.stringify(name)} is missing. Run \`npm run docs:generate\`.`,
          path,
        );
        continue;
      }
      if (readFileSync(path, "utf8") !== content) {
        bag.error(
          ErrorCode.DOCS_OUT_OF_DATE,
          `Generated document ${JSON.stringify(name)} is out of date with the profiles. Run \`npm run docs:generate\` and commit the result.`,
          path,
        );
      }
    }
  } else {
    mkdirSync(GENERATED_DOCS_DIR, { recursive: true });
    for (const [name, content] of outputs) {
      const path = join(GENERATED_DOCS_DIR, name);
      writeFileSync(path, content, "utf8");
      success(`wrote ${relative(REPO_ROOT, path)}`);
    }
  }

  const ok = reportSummary(
    check
      ? "generated documentation check"
      : `documentation generation across ${String(bundles.length)} profile(s)`,
    bag,
  );
  if (booleanFlag(args, "json")) {
    process.stdout.write(prettyJson({ ok, diagnostics: bag.toJSON() }));
  }
  return ok ? EXIT_CODES.SUCCESS : EXIT_CODES.DEFECTS_FOUND;
}

/** Render the profile index table. */
function renderProfileIndex(bundles: readonly ProfileBundle[]): string {
  const rows: {
    bundle: ProfileBundle;
    metadata: NonNullable<ProfileBundle["profile"]>["profile"];
  }[] = [];
  for (const bundle of bundles) {
    if (bundle.profile !== undefined) {
      rows.push({ bundle, metadata: bundle.profile.profile });
    }
  }
  rows.sort((left, right) => {
    const byId = compare(left.metadata.id, right.metadata.id);
    return byId !== 0 ? byId : compare(left.metadata.version, right.metadata.version);
  });

  const lines = [
    BANNER,
    "",
    "# Profile index",
    "",
    "Every profile in this repository, with the upstream revision it pins and the",
    "number of requirements it declares. Counts are of declarations, not of",
    "verified properties: conformance is decided by running the vectors against a",
    "contract, never by reading this table.",
    "",
    "| Profile | Status | Upstream | Methods | Auth rules | Events | Behaviours | Invariants | Failures | Vectors |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
  ];

  for (const { bundle, metadata } of rows) {
    const vectorCount = countVectors(bundle);
    lines.push(
      [
        `| \`${metadata.id}@${metadata.version}\``,
        metadata.status,
        `[${metadata.specification.name} v${metadata.specification.version}](${metadata.specification.url}) (${metadata.specification.status})`,
        String(bundle.methods?.length ?? 0),
        String(bundle.authorization?.length ?? 0),
        String(bundle.events?.length ?? 0),
        String(bundle.behaviors?.length ?? 0),
        String(bundle.invariants?.length ?? 0),
        String(bundle.failures?.length ?? 0),
        String(vectorCount),
      ].join(" | ") + " |",
    );
  }

  lines.push(
    "",
    "## Vector corpus digests",
    "",
    "The digest identifies an exact set of requirements, which is what a conformance",
    "receipt records so that a result can be attributed to a revision rather than to",
    '"the profile as it happened to be at the time". Vectors are hashed',
    "individually and combined in sorted order, so adding one vector does not change",
    "the contribution of any other.",
    "",
    "| Profile | Corpus digest |",
    "| --- | --- |",
  );

  for (const { bundle, metadata } of rows) {
    const digest = digestVectors(bundle.vectorFiles);
    lines.push(`| \`${metadata.id}@${metadata.version}\` | \`${digest}\` |`);
  }

  lines.push("");
  return lines.join("\n");
}

/** Render the vector index table. */
function renderVectorIndex(
  bundles: readonly ProfileBundle[],
  sharedVectors: readonly LoadedVector[],
): string {
  const rows: VectorRow[] = [];

  for (const bundle of bundles) {
    for (const vector of loadVectors(
      bundle.vectorFiles,
      getSchemaRegistry(),
      new DiagnosticBag(),
    )) {
      if (vector.vector === undefined) {
        continue;
      }
      rows.push({
        id: vector.vector.id,
        profile: vector.vector.profile,
        version: vector.vector.profile_version,
        kind: vector.vector.kind,
        method: vector.vector.method,
        location: vector.location,
      });
    }
  }
  for (const vector of sharedVectors) {
    if (vector.vector === undefined) {
      continue;
    }
    rows.push({
      id: vector.vector.id,
      profile: vector.vector.profile,
      version: vector.vector.profile_version,
      kind: vector.vector.kind,
      method: vector.vector.method,
      location: vector.location,
    });
  }

  rows.sort((left, right) => compare(left.id, right.id));

  const lines = [
    BANNER,
    "",
    "# Vector index",
    "",
    "Every vector, including the profile-independent scenarios under `vectors/common/`",
    "that declare the wildcard profile `*`. A wildcard vector belongs to no bundle and",
    "is inherited by every profile that lists `common` in `includes.shared_vectors`.",
    "",
    "| Vector | Profile | Kind | Method | Location |",
    "| --- | --- | --- | --- | --- |",
  ];

  for (const row of rows) {
    lines.push(
      `| \`${row.id}\` | \`${row.profile}@${row.version}\` | ${row.kind} | \`${row.method}\` | \`${row.location}\` |`,
    );
  }

  lines.push("", `Total: ${String(rows.length)} vector(s).`, "");
  return lines.join("\n");
}

function countVectors(bundle: ProfileBundle): number {
  return loadVectors(bundle.vectorFiles, getSchemaRegistry(), new DiagnosticBag()).filter(
    (vector) => vector.valid,
  ).length;
}

/** Digest a profile's own vectors, in sorted id order. */
function digestVectors(files: readonly string[]): string {
  const loaded = loadVectors(files, getSchemaRegistry(), new DiagnosticBag());
  const byId = new Map<string, string>();
  for (const vector of loaded) {
    if (vector.vector !== undefined) {
      byId.set(vector.vector.id, digestOfValue(vector.vector));
    }
  }
  const ordered = [...byId.entries()].sort(([left], [right]) => compare(left, right));
  // An empty corpus hashes to the digest of the empty string rather than to a
  // fabricated sentinel, so the value remains a real, reproducible digest.
  return combineDigests(ordered.map(([, digest]) => digest as `sha256:${string}`));
}

/** Enumerate the shared vector library as `<set>` to file paths. */
function readSharedVectorFiles(): ReadonlyMap<string, readonly string[]> {
  const sets = new Map<string, readonly string[]>();
  for (const set of readdirSyncSafe(VECTORS_DIR)) {
    const files: string[] = [];
    for (const operation of readdirSyncSafe(join(VECTORS_DIR, set))) {
      for (const entry of readdirSyncSafe(join(VECTORS_DIR, set, operation))) {
        if (entry.endsWith(".yaml") || entry.endsWith(".yml")) {
          files.push(join(VECTORS_DIR, set, operation, entry));
        }
      }
    }
    sets.set(set, files.sort());
  }
  return sets;
}

/** Locale-independent string comparison, so generated output is byte-stable. */
function compare(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

try {
  process.exitCode = main(process.argv.slice(2));
} catch (error) {
  handleCliError(PROGRAM, DESCRIPTION, FLAGS, error);
}
